language: python
python: 
    - 3.6
    - 3.5
    - 3.4
    - 2.7
node_js:
  - "8"
before_install:
  - npm i -g npm
install:
    - pip install tox-travis coveralls
    - npm ci
# command to run tests
script: tox
after_success: coveralls
