language: python
python: 
    - 3.6
    - 3.5
    - 3.4
    - 2.7
node_js:
  - "5.10"
install:
    - pip install tox-travis coveralls
# command to run tests
script: make test
after_success: coveralls
