language: python
# command to install dependencies
node_js:
  - "5.10"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install -q -r requirements.txt
# command to run tests
script: make test
after_success: coveralls
